export const BASE_URL = 'http://192.168.1.21:5000';
export const API_ENDPOINTS = {
  LOGIN: `${BASE_URL}/api/login`,
  REGISTER: `${BASE_URL}/api/register`,
  PROFILE: (email) => `${BASE_URL}/api/profile/${email}`,
  PROFILE_UPDATE: `${BASE_URL}/api/profile/update`,
  PROFILE_ABOUT: `${BASE_URL}/api/profile/about`,
  MANAGER_PROFILE: `${BASE_URL}/api/profile/manager`,
  TASK_UPDATES: `${BASE_URL}/api/task-updates`,
  TASKS: (userId) => `${BASE_URL}/api/tasks?userId=${userId}`,
  HOLIDAYS: `${BASE_URL}/api/holidays`,
  USERS: `${BASE_URL}/api/users`,
  THREADS: `${BASE_URL}/api/threads`,
  BIRTHDAYS: `${BASE_URL}/api/birthdays`,
  TEAMS: `${BASE_URL}/api/teams`,
  DASHBOARD_STATS: `${BASE_URL}/api/dashboard-stats`,
  ATTENDANCE: `${BASE_URL}/api/attendance`,
  ATTENDANCE_LOGS_GET: `${BASE_URL}/api/attendance_logs`,
  ALL_ATTENDANCE: `${BASE_URL}/api/attendance_logs`,
  ATTENDANCE_LOGS_BY_USER: (userId) => `${BASE_URL}/api/attendance_logs?userId=${userId}`,
  ATTENDANCE_PUNCH: `${BASE_URL}/api/attendance_logs/punch`,
  ATTENDANCE_PUNCH_UPDATE: `${BASE_URL}/api/attendance/update-punch-time`,
  ORGANIZATIONAL_ATTENDANCE: `${BASE_URL}/api/manager/attendance`,
  LEAVES_GET: `${BASE_URL}/api/leaves`,
  CEO_LEAVES_GET: `${BASE_URL}/api/ceo/leaves`,
  LEAVE_STATUS_UPDATE: (id) => `${BASE_URL}/api/leaves/${id}/status`,
  SUGGESTIONS: `${BASE_URL}/api/suggestions`,
  REWARDS_HISTORY: `${BASE_URL}/api/admin/rewards/history`,
  USER_REWARDS: (id) => `${BASE_URL}/api/rewards/user/${id}`,
  REWARDS: `${BASE_URL}/api/rewards`,
  REWARD_EDIT: (id) => `${BASE_URL}/api/rewards/${id}`,
  REWARD_DELETE: (id) => `${BASE_URL}/api/rewards/${id}`,
  REWARD_CATEGORIES: `${BASE_URL}/api/rewards/categories`,
  REWARDS_GIVE: `${BASE_URL}/api/rewards`,
  LEADERBOARD_ALL: `${BASE_URL}/api/employees/leaderboard/all`,
  SUGGESTIONS_ADMIN: `${BASE_URL}/api/suggestions/admin`,
};